import { Service } from '@angular/core';
import { ThemeFileExport, ThemeFileImport } from '@core/models/theme-designer.model';

@Service()
export class ImportExport {
    /**
     *
     * @param dataObject - the entire parsed schema object, spread together based on all the parts of the
     *   different editing sections.
     * @returns
     */
    async generateExportFile(dataObject: Partial<ThemeFileExport>): Promise<string> {
      // 1. Stringify with exact formatting (2 spaces ensures it matches exactly later)
      const jsonString = JSON.stringify(dataObject, null, 2);
  
      // 2. Generate a SHA-256 hash of the JSON string
      const msgUint8 = new TextEncoder().encode(jsonString);
      const hashBuffer = await crypto.subtle.digest('SHA-256', msgUint8);
      const hashArray = Array.from(new Uint8Array(hashBuffer));
      const hashHex = hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
  
      // 3. Write the file with the hash locked in a comment at the top
      return `/* eslint-disable */
    // Generated by https://ccl.wtf
    // Signature: ${hashHex}
    
    export default ${jsonString};`;
    }
  
    /**
     *
     * @param fileContents - the raw file that has just been stringified, via user upload. 2 Layers of security to ensure
     *  no bad actors are able to inject any malicious code in our applicatino
     * @returns
     */
    async secureImportFile(fileContents: string): Promise<any | null> {
      try {
        // 1. Extract the expected signature from the top comment
        const sigMatch = fileContents.match(/\/\/ Signature:\s*([a-f0-9]{64})/);
        if (!sigMatch) throw new Error('File is missing its security signature.');
        const expectedSignature = sigMatch[1];
  
        // 2. Use your substring method to isolate the raw JSON payload
        const firstBrace = fileContents.indexOf('{');
        const lastBrace = fileContents.lastIndexOf('}');
        if (firstBrace === -1 || lastBrace === -1) throw new Error('Malformed file structure.');
  
        const extractedJsonString = fileContents.substring(firstBrace, lastBrace + 1);
  
        // 3. Recalculate the hash of the extracted data
        const msgUint8 = new TextEncoder().encode(extractedJsonString);
        const hashBuffer = await crypto.subtle.digest('SHA-256', msgUint8);
        const hashArray = Array.from(new Uint8Array(hashBuffer));
        const actualSignature = hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
  
        // 4. Strict check: Did they tinker with it at all?
        if (expectedSignature !== actualSignature) {
          throw new Error('File integrity check failed. The file has been modified.');
        }
  
        // 5. Safe parse & Zod validation
        const rawObject = JSON.parse(extractedJsonString);
        return rawObject; // Follow this up with ThemeDesignerSchema.parse(rawObject)
      } catch (error) {
        console.error('Upload rejected:', error);
        alert('Invalid File: The file has been modified or corrupted.');
        return null;
      }
    }
  
    handleInboundSchemaSlicing(themeObject: ThemeFileImport): any {
      const fileContents = JSON.stringify(themeObject);
      // Find the first opening brace and the last closing brace
      const firstBrace = fileContents.indexOf('{');
      const lastBrace = fileContents.lastIndexOf('}');
  
      if (firstBrace === -1 || lastBrace === -1) {
        throw new Error('Invalid file structure');
      }
  
      // Extract just the object string
      const jsonString = fileContents.substring(firstBrace, lastBrace + 1);
  
      // This will work ONLY if the exported file strictly used double quotes
      const rawObject = JSON.parse(jsonString);
    }
}
