name: Deploy to GitHub Pages

on:
  push:
    branches: [ trunk ] # Triggers deployment when you push to the main branch

# Add this block right here:
defaults:
  run:
    working-directory: ./theme-designer

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment to prevent conflicts
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Using Node 22 to match your Angular version
          cache: 'npm'
          cache-dependency-path: '/theme-designer/package-lock.json'

      - name: Install Dependencies
        run: npm ci --prefix theme-designer

      - name: Generate Env and Build Angular Application
        env:
          NG_APP_PRIME_NG_KEY: ${{ secrets.NG_APP_PRIME_NG_KEY }} 
        run: npm run build-prod

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/theme-designer

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
